// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asana         *Data_Asana            `protobuf:"bytes,3,opt,name=asana,proto3" json:"asana,omitempty"`
	Docusign      *Data_Docusign         `protobuf:"bytes,4,opt,name=docusign,proto3" json:"docusign,omitempty"`
	Box           *Data_Box              `protobuf:"bytes,5,opt,name=box,proto3" json:"box,omitempty"`
	Domain        string                 `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	UseBoxSign    bool                   `protobuf:"varint,7,opt,name=use_box_sign,json=useBoxSign,proto3" json:"use_box_sign,omitempty"`
	UseAdobeSign  bool                   `protobuf:"varint,8,opt,name=use_adobe_sign,json=useAdobeSign,proto3" json:"use_adobe_sign,omitempty"`
	ResourcePath  string                 `protobuf:"bytes,9,opt,name=resource_path,json=resourcePath,proto3" json:"resource_path,omitempty"`
	SpreadsheetId string                 `protobuf:"bytes,10,opt,name=spreadsheet_id,json=spreadsheetId,proto3" json:"spreadsheet_id,omitempty"`
	Xero          *Data_Xero             `protobuf:"bytes,11,opt,name=xero,proto3" json:"xero,omitempty"`
	Zoho          *Data_Zoho             `protobuf:"bytes,12,opt,name=zoho,proto3" json:"zoho,omitempty"`
	GoogleDrive   *Data_GoogleDrive      `protobuf:"bytes,13,opt,name=google_drive,json=googleDrive,proto3" json:"google_drive,omitempty"`
	EmailMonitor  *Data_EmailMonitor     `protobuf:"bytes,14,opt,name=email_monitor,json=emailMonitor,proto3" json:"email_monitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetAsana() *Data_Asana {
	if x != nil {
		return x.Asana
	}
	return nil
}

func (x *Data) GetDocusign() *Data_Docusign {
	if x != nil {
		return x.Docusign
	}
	return nil
}

func (x *Data) GetBox() *Data_Box {
	if x != nil {
		return x.Box
	}
	return nil
}

func (x *Data) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Data) GetUseBoxSign() bool {
	if x != nil {
		return x.UseBoxSign
	}
	return false
}

func (x *Data) GetUseAdobeSign() bool {
	if x != nil {
		return x.UseAdobeSign
	}
	return false
}

func (x *Data) GetResourcePath() string {
	if x != nil {
		return x.ResourcePath
	}
	return ""
}

func (x *Data) GetSpreadsheetId() string {
	if x != nil {
		return x.SpreadsheetId
	}
	return ""
}

func (x *Data) GetXero() *Data_Xero {
	if x != nil {
		return x.Xero
	}
	return nil
}

func (x *Data) GetZoho() *Data_Zoho {
	if x != nil {
		return x.Zoho
	}
	return nil
}

func (x *Data) GetGoogleDrive() *Data_GoogleDrive {
	if x != nil {
		return x.GoogleDrive
	}
	return nil
}

func (x *Data) GetEmailMonitor() *Data_EmailMonitor {
	if x != nil {
		return x.EmailMonitor
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Asana struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiHost       string                 `protobuf:"bytes,1,opt,name=api_host,json=apiHost,proto3" json:"api_host,omitempty"`
	Pat           string                 `protobuf:"bytes,2,opt,name=pat,proto3" json:"pat,omitempty"`
	ProjectGid    string                 `protobuf:"bytes,3,opt,name=project_gid,json=projectGid,proto3" json:"project_gid,omitempty"`
	ProjectGidCp  string                 `protobuf:"bytes,4,opt,name=project_gid_cp,json=projectGidCp,proto3" json:"project_gid_cp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Asana) Reset() {
	*x = Data_Asana{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Asana) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Asana) ProtoMessage() {}

func (x *Data_Asana) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Asana.ProtoReflect.Descriptor instead.
func (*Data_Asana) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Asana) GetApiHost() string {
	if x != nil {
		return x.ApiHost
	}
	return ""
}

func (x *Data_Asana) GetPat() string {
	if x != nil {
		return x.Pat
	}
	return ""
}

func (x *Data_Asana) GetProjectGid() string {
	if x != nil {
		return x.ProjectGid
	}
	return ""
}

func (x *Data_Asana) GetProjectGidCp() string {
	if x != nil {
		return x.ProjectGidCp
	}
	return ""
}

type Data_Docusign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppAccountId  string                 `protobuf:"bytes,1,opt,name=app_account_id,json=appAccountId,proto3" json:"app_account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Docusign) Reset() {
	*x = Data_Docusign{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Docusign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Docusign) ProtoMessage() {}

func (x *Data_Docusign) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Docusign.ProtoReflect.Descriptor instead.
func (*Data_Docusign) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Docusign) GetAppAccountId() string {
	if x != nil {
		return x.AppAccountId
	}
	return ""
}

type Data_Box struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	ApiUrl                           string                 `protobuf:"bytes,1,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`
	UploadUrl                        string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	NewClientFolderStructureId       string                 `protobuf:"bytes,3,opt,name=new_client_folder_structure_id,json=newClientFolderStructureId,proto3" json:"new_client_folder_structure_id,omitempty"`
	ClientFolderStructureParentId    string                 `protobuf:"bytes,4,opt,name=client_folder_structure_parent_id,json=clientFolderStructureParentId,proto3" json:"client_folder_structure_parent_id,omitempty"`
	ClientFolderStructureParentIdV2  string                 `protobuf:"bytes,5,opt,name=client_folder_structure_parent_id_v2,json=clientFolderStructureParentIdV2,proto3" json:"client_folder_structure_parent_id_v2,omitempty"`
	ClientContractsId                string                 `protobuf:"bytes,6,opt,name=client_contracts_id,json=clientContractsId,proto3" json:"client_contracts_id,omitempty"`
	NewDataCollectionFolderStructure string                 `protobuf:"bytes,7,opt,name=new_data_collection_folder_structure,json=newDataCollectionFolderStructure,proto3" json:"new_data_collection_folder_structure,omitempty"`
	DataCollectionFolderId           string                 `protobuf:"bytes,8,opt,name=data_collection_folder_id,json=dataCollectionFolderId,proto3" json:"data_collection_folder_id,omitempty"`
	DataCollectionFolderIdV2         string                 `protobuf:"bytes,9,opt,name=data_collection_folder_id_v2,json=dataCollectionFolderIdV2,proto3" json:"data_collection_folder_id_v2,omitempty"`
	SyncRecordReviewVersion          int32                  `protobuf:"varint,10,opt,name=sync_record_review_version,json=syncRecordReviewVersion,proto3" json:"sync_record_review_version,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *Data_Box) Reset() {
	*x = Data_Box{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Box) ProtoMessage() {}

func (x *Data_Box) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Box.ProtoReflect.Descriptor instead.
func (*Data_Box) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Data_Box) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

func (x *Data_Box) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *Data_Box) GetNewClientFolderStructureId() string {
	if x != nil {
		return x.NewClientFolderStructureId
	}
	return ""
}

func (x *Data_Box) GetClientFolderStructureParentId() string {
	if x != nil {
		return x.ClientFolderStructureParentId
	}
	return ""
}

func (x *Data_Box) GetClientFolderStructureParentIdV2() string {
	if x != nil {
		return x.ClientFolderStructureParentIdV2
	}
	return ""
}

func (x *Data_Box) GetClientContractsId() string {
	if x != nil {
		return x.ClientContractsId
	}
	return ""
}

func (x *Data_Box) GetNewDataCollectionFolderStructure() string {
	if x != nil {
		return x.NewDataCollectionFolderStructure
	}
	return ""
}

func (x *Data_Box) GetDataCollectionFolderId() string {
	if x != nil {
		return x.DataCollectionFolderId
	}
	return ""
}

func (x *Data_Box) GetDataCollectionFolderIdV2() string {
	if x != nil {
		return x.DataCollectionFolderIdV2
	}
	return ""
}

func (x *Data_Box) GetSyncRecordReviewVersion() int32 {
	if x != nil {
		return x.SyncRecordReviewVersion
	}
	return 0
}

type Data_Xero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiUrl        string                 `protobuf:"bytes,1,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Xero) Reset() {
	*x = Data_Xero{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Xero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Xero) ProtoMessage() {}

func (x *Data_Xero) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Xero.ProtoReflect.Descriptor instead.
func (*Data_Xero) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Data_Xero) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

func (x *Data_Xero) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type Data_Zoho struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiUrl        string                 `protobuf:"bytes,1,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Zoho) Reset() {
	*x = Data_Zoho{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Zoho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Zoho) ProtoMessage() {}

func (x *Data_Zoho) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Zoho.ProtoReflect.Descriptor instead.
func (*Data_Zoho) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 4}
}

func (x *Data_Zoho) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

type Data_GoogleDrive struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	PaymentsFolderId           string                 `protobuf:"bytes,1,opt,name=payments_folder_id,json=paymentsFolderId,proto3" json:"payments_folder_id,omitempty"`
	PsychEvaluationsFolderId   string                 `protobuf:"bytes,2,opt,name=psych_evaluations_folder_id,json=psychEvaluationsFolderId,proto3" json:"psych_evaluations_folder_id,omitempty"`
	MedicalEvaluationsFolderId string                 `protobuf:"bytes,3,opt,name=medical_evaluations_folder_id,json=medicalEvaluationsFolderId,proto3" json:"medical_evaluations_folder_id,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Data_GoogleDrive) Reset() {
	*x = Data_GoogleDrive{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_GoogleDrive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_GoogleDrive) ProtoMessage() {}

func (x *Data_GoogleDrive) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_GoogleDrive.ProtoReflect.Descriptor instead.
func (*Data_GoogleDrive) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 5}
}

func (x *Data_GoogleDrive) GetPaymentsFolderId() string {
	if x != nil {
		return x.PaymentsFolderId
	}
	return ""
}

func (x *Data_GoogleDrive) GetPsychEvaluationsFolderId() string {
	if x != nil {
		return x.PsychEvaluationsFolderId
	}
	return ""
}

func (x *Data_GoogleDrive) GetMedicalEvaluationsFolderId() string {
	if x != nil {
		return x.MedicalEvaluationsFolderId
	}
	return ""
}

type Data_EmailMonitor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Cc               []string               `protobuf:"bytes,1,rep,name=cc,proto3" json:"cc,omitempty"`
	ReForwardSeconds int32                  `protobuf:"varint,2,opt,name=re_forward_seconds,json=reForwardSeconds,proto3" json:"re_forward_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Data_EmailMonitor) Reset() {
	*x = Data_EmailMonitor{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_EmailMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_EmailMonitor) ProtoMessage() {}

func (x *Data_EmailMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_EmailMonitor.ProtoReflect.Descriptor instead.
func (*Data_EmailMonitor) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 6}
}

func (x *Data_EmailMonitor) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *Data_EmailMonitor) GetReForwardSeconds() int32 {
	if x != nil {
		return x.ReForwardSeconds
	}
	return 0
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"]\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x8b\r\n" +
	"\x04Data\x12,\n" +
	"\x05asana\x18\x03 \x01(\v2\x16.kratos.api.Data.AsanaR\x05asana\x125\n" +
	"\bdocusign\x18\x04 \x01(\v2\x19.kratos.api.Data.DocusignR\bdocusign\x12&\n" +
	"\x03box\x18\x05 \x01(\v2\x14.kratos.api.Data.BoxR\x03box\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\x12 \n" +
	"\fuse_box_sign\x18\a \x01(\bR\n" +
	"useBoxSign\x12$\n" +
	"\x0euse_adobe_sign\x18\b \x01(\bR\fuseAdobeSign\x12#\n" +
	"\rresource_path\x18\t \x01(\tR\fresourcePath\x12%\n" +
	"\x0espreadsheet_id\x18\n" +
	" \x01(\tR\rspreadsheetId\x12)\n" +
	"\x04xero\x18\v \x01(\v2\x15.kratos.api.Data.XeroR\x04xero\x12)\n" +
	"\x04zoho\x18\f \x01(\v2\x15.kratos.api.Data.ZohoR\x04zoho\x12?\n" +
	"\fgoogle_drive\x18\r \x01(\v2\x1c.kratos.api.Data.GoogleDriveR\vgoogleDrive\x12B\n" +
	"\remail_monitor\x18\x0e \x01(\v2\x1d.kratos.api.Data.EmailMonitorR\femailMonitor\x1a{\n" +
	"\x05Asana\x12\x19\n" +
	"\bapi_host\x18\x01 \x01(\tR\aapiHost\x12\x10\n" +
	"\x03pat\x18\x02 \x01(\tR\x03pat\x12\x1f\n" +
	"\vproject_gid\x18\x03 \x01(\tR\n" +
	"projectGid\x12$\n" +
	"\x0eproject_gid_cp\x18\x04 \x01(\tR\fprojectGidCp\x1a0\n" +
	"\bDocusign\x12$\n" +
	"\x0eapp_account_id\x18\x01 \x01(\tR\fappAccountId\x1a\xd2\x04\n" +
	"\x03Box\x12\x17\n" +
	"\aapi_url\x18\x01 \x01(\tR\x06apiUrl\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12B\n" +
	"\x1enew_client_folder_structure_id\x18\x03 \x01(\tR\x1anewClientFolderStructureId\x12H\n" +
	"!client_folder_structure_parent_id\x18\x04 \x01(\tR\x1dclientFolderStructureParentId\x12M\n" +
	"$client_folder_structure_parent_id_v2\x18\x05 \x01(\tR\x1fclientFolderStructureParentIdV2\x12.\n" +
	"\x13client_contracts_id\x18\x06 \x01(\tR\x11clientContractsId\x12N\n" +
	"$new_data_collection_folder_structure\x18\a \x01(\tR newDataCollectionFolderStructure\x129\n" +
	"\x19data_collection_folder_id\x18\b \x01(\tR\x16dataCollectionFolderId\x12>\n" +
	"\x1cdata_collection_folder_id_v2\x18\t \x01(\tR\x18dataCollectionFolderIdV2\x12;\n" +
	"\x1async_record_review_version\x18\n" +
	" \x01(\x05R\x17syncRecordReviewVersion\x1a<\n" +
	"\x04Xero\x12\x17\n" +
	"\aapi_url\x18\x01 \x01(\tR\x06apiUrl\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x1a\x1f\n" +
	"\x04Zoho\x12\x17\n" +
	"\aapi_url\x18\x01 \x01(\tR\x06apiUrl\x1a\xbd\x01\n" +
	"\vGoogleDrive\x12,\n" +
	"\x12payments_folder_id\x18\x01 \x01(\tR\x10paymentsFolderId\x12=\n" +
	"\x1bpsych_evaluations_folder_id\x18\x02 \x01(\tR\x18psychEvaluationsFolderId\x12A\n" +
	"\x1dmedical_evaluations_folder_id\x18\x03 \x01(\tR\x1amedicalEvaluationsFolderId\x1aL\n" +
	"\fEmailMonitor\x12\x0e\n" +
	"\x02cc\x18\x01 \x03(\tR\x02cc\x12,\n" +
	"\x12re_forward_seconds\x18\x02 \x01(\x05R\x10reForwardSecondsB\x18Z\x16vbc/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*Server_HTTP)(nil),         // 3: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 4: kratos.api.Server.GRPC
	(*Data_Asana)(nil),          // 5: kratos.api.Data.Asana
	(*Data_Docusign)(nil),       // 6: kratos.api.Data.Docusign
	(*Data_Box)(nil),            // 7: kratos.api.Data.Box
	(*Data_Xero)(nil),           // 8: kratos.api.Data.Xero
	(*Data_Zoho)(nil),           // 9: kratos.api.Data.Zoho
	(*Data_GoogleDrive)(nil),    // 10: kratos.api.Data.GoogleDrive
	(*Data_EmailMonitor)(nil),   // 11: kratos.api.Data.EmailMonitor
	(*durationpb.Duration)(nil), // 12: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	4,  // 3: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	5,  // 4: kratos.api.Data.asana:type_name -> kratos.api.Data.Asana
	6,  // 5: kratos.api.Data.docusign:type_name -> kratos.api.Data.Docusign
	7,  // 6: kratos.api.Data.box:type_name -> kratos.api.Data.Box
	8,  // 7: kratos.api.Data.xero:type_name -> kratos.api.Data.Xero
	9,  // 8: kratos.api.Data.zoho:type_name -> kratos.api.Data.Zoho
	10, // 9: kratos.api.Data.google_drive:type_name -> kratos.api.Data.GoogleDrive
	11, // 10: kratos.api.Data.email_monitor:type_name -> kratos.api.Data.EmailMonitor
	12, // 11: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	12, // 12: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
