package config_zoho

/*
重要说明：
- Leads和Contacts底层数据，是不相同的。
- 因为Leads与Contacts的字段名称差不多， 所以使用Contacts的字段名，查Leads可以出结果， 但有风险。
- Deals关联的Contacts的ID，在Leads查不到。
*/
const Leads = "Leads"
const Contacts = "Contacts"
const Deals = "Deals"
const Tasks = "Tasks"
const Notes = "Notes"

var Modules = `{
	"modules": [{
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-04T10:33:21+08:00",
		"plural_label": "Accounts",
		"presence_sub_menu": false,
		"actual_plural_label": "Accounts",
		"id": "6159272000000002177",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": false,
		"actual_singular_label": "Account",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}],
		"show_as_tab": true,
		"web_link": null,
		"singular_label": "Account",
		"viewable": false,
		"api_supported": true,
		"api_name": "Accounts",
		"quick_create": false,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Accounts",
		"profile_count": 1,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "user_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-04T10:34:24+08:00",
		"plural_label": "Cases",
		"presence_sub_menu": false,
		"actual_plural_label": "Cases",
		"id": "6159272000000002209",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Case",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"singular_label": "Case",
		"viewable": true,
		"api_supported": true,
		"api_name": "Cases",
		"quick_create": false,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Cases",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "user_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-04T10:34:24+08:00",
		"plural_label": "Solutions",
		"presence_sub_menu": false,
		"actual_plural_label": "Solutions",
		"id": "6159272000000002211",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Solution",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"singular_label": "Solution",
		"viewable": true,
		"api_supported": true,
		"api_name": "Solutions",
		"quick_create": false,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Solutions",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "user_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-04T10:34:24+08:00",
		"plural_label": "Vendors",
		"presence_sub_menu": false,
		"actual_plural_label": "Vendors",
		"id": "6159272000000002215",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Vendor",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"singular_label": "Vendor",
		"viewable": true,
		"api_supported": true,
		"api_name": "Vendors",
		"quick_create": false,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Vendors",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "user_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-04T10:34:24+08:00",
		"plural_label": "Price Books",
		"presence_sub_menu": false,
		"actual_plural_label": "Price Books",
		"id": "6159272000000002217",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Price Book",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"singular_label": "Price Book",
		"viewable": true,
		"api_supported": true,
		"api_name": "Price_Books",
		"quick_create": false,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "PriceBooks",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "user_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-04T10:34:24+08:00",
		"plural_label": "Quotes",
		"presence_sub_menu": false,
		"actual_plural_label": "Quotes",
		"id": "6159272000000002219",
		"visibility": 1,
		"convertable": true,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Quote",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"singular_label": "Quote",
		"viewable": true,
		"api_supported": true,
		"api_name": "Quotes",
		"quick_create": false,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Quotes",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "user_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-04T10:34:24+08:00",
		"plural_label": "Sales Orders",
		"presence_sub_menu": false,
		"actual_plural_label": "Sales Orders",
		"id": "6159272000000002221",
		"visibility": 1,
		"convertable": true,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Sales Order",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"singular_label": "Sales Order",
		"viewable": true,
		"api_supported": true,
		"api_name": "Sales_Orders",
		"quick_create": false,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "SalesOrders",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "user_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-04T10:34:24+08:00",
		"plural_label": "Purchase Orders",
		"presence_sub_menu": false,
		"actual_plural_label": "Purchase Orders",
		"id": "6159272000000002223",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Purchase Order",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"singular_label": "Purchase Order",
		"viewable": true,
		"api_supported": true,
		"api_name": "Purchase_Orders",
		"quick_create": false,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "PurchaseOrders",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "user_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": "2024-03-04T10:34:24+08:00",
		"plural_label": "SalesInbox",
		"presence_sub_menu": false,
		"actual_plural_label": "SalesInbox",
		"id": "6159272000000118001",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "SalesInbox",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"singular_label": "SalesInbox",
		"viewable": false,
		"api_supported": false,
		"api_name": "SalesInbox",
		"quick_create": false,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "SalesInbox",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "user_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Home",
		"presence_sub_menu": false,
		"actual_plural_label": "Home",
		"id": "6159272000000002173",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Home",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 1,
		"singular_label": "Home",
		"viewable": true,
		"api_supported": false,
		"api_name": "Home",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Home",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-10T11:48:52+08:00",
		"plural_label": "Leads",
		"presence_sub_menu": true,
		"actual_plural_label": "Leads",
		"id": "6159272000000002175",
		"visibility": 1,
		"convertable": true,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Lead",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 2,
		"singular_label": "Lead",
		"viewable": true,
		"api_supported": true,
		"api_name": "Leads",
		"quick_create": true,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Leads",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-07T14:24:52+08:00",
		"plural_label": "Clients",
		"presence_sub_menu": true,
		"actual_plural_label": "Clients",
		"id": "6159272000000002179",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Client",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 3,
		"singular_label": "Client",
		"viewable": true,
		"api_supported": true,
		"api_name": "Contacts",
		"quick_create": true,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Contacts",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": "2024-03-10T11:36:46+08:00",
		"plural_label": "Client Cases",
		"presence_sub_menu": true,
		"actual_plural_label": "Client Cases",
		"id": "6159272000000002181",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Client Case",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 4,
		"singular_label": "Client Case",
		"viewable": true,
		"api_supported": true,
		"api_name": "Deals",
		"quick_create": true,
		"modified_by": {
			"name": "Yannan Wang",
			"id": "6159272000000453001"
		},
		"generated_type": "default",
		"feeds_required": true,
		"arguments": [],
		"module_name": "Deals",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": null,
		"plural_label": "Tasks",
		"presence_sub_menu": true,
		"actual_plural_label": "Tasks",
		"id": "6159272000000002193",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Task",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 5,
		"singular_label": "Task",
		"viewable": true,
		"api_supported": true,
		"api_name": "Tasks",
		"quick_create": true,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Tasks",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": null,
		"plural_label": "Meetings",
		"presence_sub_menu": true,
		"actual_plural_label": "Meetings",
		"id": "6159272000000002195",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Meeting",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 6,
		"singular_label": "Meeting",
		"viewable": true,
		"api_supported": true,
		"api_name": "Events",
		"quick_create": true,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Meetings",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": null,
		"plural_label": "Calls",
		"presence_sub_menu": true,
		"actual_plural_label": "Calls",
		"id": "6159272000000033015",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Call",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 7,
		"singular_label": "Call",
		"viewable": true,
		"api_supported": true,
		"api_name": "Calls",
		"quick_create": true,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Calls",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Reports",
		"presence_sub_menu": false,
		"actual_plural_label": "Reports",
		"id": "6159272000000002185",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Report",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 8,
		"singular_label": "Report",
		"viewable": true,
		"api_supported": false,
		"api_name": "Reports",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Reports",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Analytics",
		"presence_sub_menu": false,
		"actual_plural_label": "Analytics",
		"id": "6159272000000002187",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Analytics",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 9,
		"singular_label": "Analytics",
		"viewable": true,
		"api_supported": false,
		"api_name": "Analytics",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Dashboards",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": null,
		"plural_label": "Products",
		"presence_sub_menu": true,
		"actual_plural_label": "Products",
		"id": "6159272000000002213",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Product",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 10,
		"singular_label": "Product",
		"viewable": true,
		"api_supported": true,
		"api_name": "Products",
		"quick_create": true,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Products",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": null,
		"plural_label": "Invoices",
		"presence_sub_menu": true,
		"actual_plural_label": "Invoices",
		"id": "6159272000000002225",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Invoice",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 11,
		"singular_label": "Invoice",
		"viewable": true,
		"api_supported": true,
		"api_name": "Invoices",
		"quick_create": true,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Invoices",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": null,
		"plural_label": "Campaigns",
		"presence_sub_menu": true,
		"actual_plural_label": "Campaigns",
		"id": "6159272000000002183",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": true,
		"actual_singular_label": "Campaign",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 12,
		"singular_label": "Campaign",
		"viewable": true,
		"api_supported": true,
		"api_name": "Campaigns",
		"quick_create": true,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Campaigns",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Documents",
		"presence_sub_menu": false,
		"actual_plural_label": "Documents",
		"id": "6159272000000056001",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Documents",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 13,
		"singular_label": "Documents",
		"viewable": true,
		"api_supported": false,
		"api_name": "Documents",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Documents",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Forecasts",
		"presence_sub_menu": true,
		"actual_plural_label": "Forecasts",
		"id": "6159272000000002201",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": true,
		"editable": false,
		"actual_singular_label": "Forecast",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 14,
		"singular_label": "Forecast",
		"viewable": true,
		"api_supported": false,
		"api_name": "Forecasts",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Forecasts",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Feeds",
		"presence_sub_menu": false,
		"actual_plural_label": "Feeds",
		"id": "6159272000000071001",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Feeds",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 15,
		"singular_label": "Feeds",
		"viewable": true,
		"api_supported": false,
		"api_name": "Feeds",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Feeds",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "user_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Visits",
		"presence_sub_menu": false,
		"actual_plural_label": "Visits",
		"id": "6159272000000077007",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Visit",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 15,
		"singular_label": "Visit",
		"viewable": false,
		"api_supported": true,
		"api_name": "Visits",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Visits",
		"profile_count": 1,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Social",
		"presence_sub_menu": false,
		"actual_plural_label": "Social",
		"id": "6159272000000065001",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Social",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 16,
		"singular_label": "Social",
		"viewable": false,
		"api_supported": false,
		"api_name": "Social",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Social",
		"profile_count": 1,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "My Jobs",
		"presence_sub_menu": false,
		"actual_plural_label": "My Jobs",
		"id": "6159272000000463158",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "My Jobs",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 17,
		"singular_label": "My Jobs",
		"viewable": true,
		"api_supported": true,
		"api_name": "Approvals",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Approvals",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"track_current_data": true,
		"plural_label": "Stage History",
		"presence_sub_menu": false,
		"actual_plural_label": "Stage History",
		"id": "6159272000000174001",
		"visibility": 2,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Stage History",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 24,
		"singular_label": "Stage History",
		"viewable": true,
		"api_supported": true,
		"api_name": "DealHistory",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "field_tracker",
		"feeds_required": false,
		"arguments": [],
		"module_name": "DealHistory",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {
			"api_name": "Deals",
			"id": "6159272000000002181"
		},
		"status": "system_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "EmailSentiment",
		"presence_sub_menu": false,
		"actual_plural_label": "EmailSentiment",
		"id": "6159272000000197001",
		"visibility": 2,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "EmailSentiment",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 24,
		"singular_label": "EmailSentiment",
		"viewable": false,
		"api_supported": true,
		"api_name": "Email_Sentiment",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "EmailSentiment",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Email Analytics",
		"presence_sub_menu": false,
		"actual_plural_label": "Email Analytics",
		"id": "6159272000000246017",
		"visibility": 2,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Email Analytics",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 24,
		"singular_label": "Email Analytics",
		"viewable": false,
		"api_supported": true,
		"api_name": "Email_Analytics",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Email Analytics",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Email Template Analytics",
		"presence_sub_menu": false,
		"actual_plural_label": "Email Template Analytics",
		"id": "6159272000000246114",
		"visibility": 2,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Email Template Analytics",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 24,
		"singular_label": "Email Template Analytics",
		"viewable": false,
		"api_supported": true,
		"api_name": "Email_Template_Analytics",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Email Template Analytics",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": true,
		"modified_time": null,
		"plural_label": "Invoiced Items",
		"presence_sub_menu": false,
		"actual_plural_label": "Invoiced Items",
		"id": "6159272000000234255",
		"visibility": 2,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Invoiced Items",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 26,
		"singular_label": "Invoiced Items",
		"viewable": true,
		"api_supported": true,
		"api_name": "Invoiced_Items",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "subform",
		"feeds_required": false,
		"arguments": [],
		"module_name": "InvoicedItems",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {
			"api_name": "Invoices",
			"id": "6159272000000002225"
		},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": true,
		"modified_time": null,
		"plural_label": "Notes",
		"presence_sub_menu": false,
		"actual_plural_label": "Notes",
		"id": "6159272000000002197",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": true,
		"actual_singular_label": "Note",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 29,
		"singular_label": "Note",
		"viewable": true,
		"api_supported": true,
		"api_name": "Notes",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Notes",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "system_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": true,
		"description": null,
		"creatable": true,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Attachments",
		"presence_sub_menu": false,
		"actual_plural_label": "Attachments",
		"id": "6159272000000002227",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Attachment",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 33,
		"singular_label": "Attachment",
		"viewable": true,
		"api_supported": true,
		"api_name": "Attachments",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Attachments",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "system_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Emails",
		"presence_sub_menu": false,
		"actual_plural_label": "Emails",
		"id": "6159272000000014163",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Email",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": true,
		"web_link": null,
		"sequence_number": 34,
		"singular_label": "Email",
		"viewable": false,
		"api_supported": false,
		"api_name": "Emails",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Emails",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Actions Performed",
		"presence_sub_menu": false,
		"actual_plural_label": "Actions Performed",
		"id": "6159272000000137005",
		"visibility": 1,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Actions Performed",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 39,
		"singular_label": "Actions Performed",
		"viewable": true,
		"api_supported": true,
		"api_name": "Actions_Performed",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Actions Performed",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "system_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "ShiftHours",
		"presence_sub_menu": false,
		"actual_plural_label": "ShiftHours",
		"id": "6159272000000284011",
		"visibility": 14334,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "ShiftHour",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 56,
		"singular_label": "ShiftHour",
		"viewable": false,
		"api_supported": false,
		"api_name": "ShiftHours",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "ShiftHours",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Forecast Quotas",
		"presence_sub_menu": false,
		"actual_plural_label": "Forecast Quotas",
		"id": "6159272000000308015",
		"visibility": 736,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Forecast Quota",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 57,
		"singular_label": "Forecast Quota",
		"viewable": false,
		"api_supported": false,
		"api_name": "Forecast_Quotas",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Forecast Quotas",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "system_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Forecast Items",
		"presence_sub_menu": false,
		"actual_plural_label": "Forecast Items",
		"id": "6159272000000308017",
		"visibility": 736,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Forecast Item",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 57,
		"singular_label": "Forecast Item",
		"viewable": false,
		"api_supported": false,
		"api_name": "Forecast_Items",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Forecast Items",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "system_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Forecast Groups",
		"presence_sub_menu": false,
		"actual_plural_label": "Forecast Groups",
		"id": "6159272000000308025",
		"visibility": 2044,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Forecast Group",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 57,
		"singular_label": "Forecast Group",
		"viewable": false,
		"api_supported": false,
		"api_name": "Forecast_Groups",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "Forecast Groups",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "system_hidden"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": "contains monthly stats of data enrichment for an enabled module",
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Data Enrichment Stats",
		"presence_sub_menu": false,
		"actual_plural_label": "Data Enrichment Stats",
		"id": "6159272000000380015",
		"visibility": 2046,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Data Enrichment Stats",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 65,
		"singular_label": "Data Enrichment Stats",
		"viewable": false,
		"api_supported": true,
		"api_name": "Data_Enrichment_Stats__s",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "DataEnrichmentStats",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}, {
		"has_more_profiles": false,
		"deletable": false,
		"description": null,
		"creatable": false,
		"recycle_bin_on_delete": false,
		"modified_time": null,
		"plural_label": "Locking Information",
		"presence_sub_menu": false,
		"actual_plural_label": "Locking Information",
		"id": "6159272000000375001",
		"visibility": 2,
		"convertable": false,
		"sub_menu_available": false,
		"editable": false,
		"actual_singular_label": "Locking Information",
		"profiles": [{
			"name": "Administrator",
			"id": "6159272000000026011"
		}, {
			"name": "Standard",
			"id": "6159272000000026014"
		}, {
			"name": "Engineering",
			"id": "6159272000000453653"
		}],
		"show_as_tab": false,
		"web_link": null,
		"sequence_number": 70,
		"singular_label": "Locking Information",
		"viewable": false,
		"api_supported": true,
		"api_name": "Locking_Information__s",
		"quick_create": false,
		"modified_by": null,
		"generated_type": "default",
		"feeds_required": false,
		"arguments": [],
		"module_name": "LockingInformation",
		"profile_count": 3,
		"business_card_field_limit": 5,
		"parent_module": {},
		"status": "visible"
	}]
}`
